/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntru_NTRU */

#ifndef _Included_ntru_NTRU
#define _Included_ntru_NTRU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ntru_NTRU
 * Method:    decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ntru_NTRU_decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     ntru_NTRU
 * Method:    encrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ntru_NTRU_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     ntru_NTRU
 * Method:    keyPair
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ntru_NTRU_keyPair
  (JNIEnv *, jclass);

/*
 * Class:     ntru_NTRU
 * Method:    publicKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_ntru_NTRU_publicKey
  (JNIEnv *, jclass);

/*
 * Class:     ntru_NTRU
 * Method:    privateKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_ntru_NTRU_privateKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
